#!/bin/bash

# Propulsion - Local Development Setup Script
# This script helps you configure your local environment

set -e

echo "🚀 Propulsion Local Development Setup"
echo "======================================"
echo ""

# Check if .env.local exists
if [ -f ".env.local" ]; then
    echo "⚠️  .env.local already exists. Backing it up to .env.local.backup"
    cp .env.local .env.local.backup
fi

# Prompt for backend URL
echo "Where is your backend running?"
echo "1) Local backend (http://localhost:8000)"
echo "2) ngrok tunnel (I'll provide the URL)"
echo "3) Deployed backend (I'll provide the URL)"
echo ""
read -p "Enter your choice (1-3): " choice

case $choice in
    1)
        BACKEND_URL="http://localhost:8000"
        echo "✅ Using local backend: $BACKEND_URL"
        ;;
    2)
        read -p "Enter your ngrok URL (e.g., https://abc123.ngrok.io): " ngrok_url
        BACKEND_URL="$ngrok_url"
        echo "✅ Using ngrok backend: $BACKEND_URL"
        ;;
    3)
        read -p "Enter your deployed backend URL: " deployed_url
        BACKEND_URL="$deployed_url"
        echo "✅ Using deployed backend: $BACKEND_URL"
        ;;
    *)
        echo "❌ Invalid choice. Defaulting to localhost."
        BACKEND_URL="http://localhost:8000"
        ;;
esac

# Create .env.local
cat > .env.local << EOF
# Local Development Environment Variables
# Generated by setup script on $(date)

# Backend API URL
NEXT_PUBLIC_API_URL=$BACKEND_URL
EOF

echo ""
echo "✅ Created .env.local with:"
echo "   NEXT_PUBLIC_API_URL=$BACKEND_URL"
echo ""

# Check if ngrok config needs updating
if [ -f "ngrok.yml" ]; then
    if grep -q "YOUR_NGROK_AUTH_TOKEN" ngrok.yml; then
        echo "⚠️  ngrok.yml still has placeholder authtoken"
        echo "   Get your token from: https://dashboard.ngrok.com/get-started/your-authtoken"
        echo ""
        read -p "Do you want to update it now? (y/n): " update_ngrok
        if [ "$update_ngrok" = "y" ]; then
            read -p "Enter your ngrok authtoken: " ngrok_token
            sed -i.bak "s/YOUR_NGROK_AUTH_TOKEN/$ngrok_token/" ngrok.yml
            echo "✅ Updated ngrok.yml with your authtoken"
        fi
    fi
fi

echo ""
echo "🎉 Setup complete!"
echo ""
echo "Next steps:"
echo "1. Start your backend (if running locally):"
echo "   cd backend && uvicorn app.main:app --reload"
echo ""
echo "2. Start your frontend:"
echo "   npm run dev"
echo ""
echo "3. (Optional) Start ngrok tunnels:"
echo "   ngrok start --all --config=ngrok.yml"
echo ""
